# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateGridsAngle
                                 A QGIS plugin
 Create grids under specific angle
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-01
        copyright            : (C) 2024 by Memic Emir
        email                : emir_memic@windowslive.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateGridsAngle class from file CreateGridsAngle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_grids_angle import CreateGridsAngle
    return CreateGridsAngle(iface)
